# Generated by Django 5.2.5 on 2025-08-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
    ]
