# Generated by Django 5.2.5 on 2025-08-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotelimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
