# Generated by Django 5.2.5 on 2025-09-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotelimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='uploaded_at',
        ),
    ]
