# Generated by Django 5.2.5 on 2025-08-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_booking_num_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
