# Generated by Django 5.2.5 on 2025-08-21 02:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default description', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
